### ISSUE TITLE
pager schedule $SCHEDULE no longer returns anything

### ISSUE THREAD

**Issue by TheFynx** [hubot-scripts/hubot-pager-me#64]
With 2.18, you can no longer return a specific schedule, merge [63](https://github.com/hubot-scripts/hubot-pager-me/pull/63) refactored most of this functionality, I  think there's still a rogue reference to the [oneScheduleMatching](https://github.com/mmrobins/hubot-pager-me/blob/master/src/scripts/pagerduty.coffee#L720) variable that was changed in the aforementioned merge.

**Comment by aaronblythe** [comment]
:+1: Looks good.

**Comment by stephenyeargin** [comment]
Fixed via #65

**Comment by mmrobins** [comment]
was gonna look tonight, but glad @TheFynx got a fix in so quick, thx.  It's hard to modify code without tests like this.

**Comment by TheFynx** [comment]
@mmrobins well, I may have not fixed it completely. I'll continue testing, but seems some of the stuff doesn't like hipchat. who's on call for <schedule> has issues and it won't return schedule <schedule> in hipchat (too many adapters...). I'll do some more testing and open up another issue.
